### ISSUE TITLE
Blood Potency Changes on Character Sheets Don't Match with 5E Table[BUG]

### ISSUE THREAD

**Issue by chaosgasket** [Rayji96/foundry-V5#190]
**Describe the bug**
When making a Vampire character sheet, changes to Blood Potency don't change Blood Surge and Bane Severity to match up with the 5E table on page 216 of the rule book. At Blood Potency 0 it shows Blood Surge as adding 1 die, when it should be 0. At Blood Potency 1, it shows Blood Surge as adding 2 dice, which should be 1, and a Bane Severity of 2, which should be 1.  These issues then continue through the higher levels of Blood Potency

**To Reproduce**
Adding additional dots of Blood Potency on a vampire character sheet make automatic changes to the other stats on that page.

**Expected behavior**
I would expect the changes to match the table in the rulebook.

**Screenshots**

![Screenshot 2023-06-17 112637](https://github.com/Rayji96/foundry-V5/assets/99540375/f05e9787-5ada-45e0-b4e4-9768c2f4a343)
![Screenshot 2023-06-17 112648](https://github.com/Rayji96/foundry-V5/assets/99540375/3ab332a9-6bf3-45a1-8fb9-958b72db5db5)
![Screenshot 2023-06-17 112654](https://github.com/Rayji96/foundry-V5/assets/99540375/dbdecb76-5b95-46a1-adfe-3f3d6a1dd169)

**Desktop**

- FoundryVTT Version [11.302]

**Additional context**

**Comment by eisenfuchs** [comment]
Your screenshots are for BP 1 and BP 2 respectively. You haven't included a BP 0 screenshot, are you sure it's a bug? I remember this has been fixed ages ago?

**Comment by chaosgasket** [comment]
It's still wrong for BP 1 and BP 2, BP 1 and 2 should only have 1 die of Blood Surge and 1 Bane Potency.

Here's a screenshot of BP 0, should have 0 die of Blood Surge:
![Screenshot 2023-06-17 115248](https://github.com/Rayji96/foundry-V5/assets/99540375/fbe65fed-5f59-4321-bc35-4742ad0e8409)

**Comment by eisenfuchs** [comment]
I found the problem.

You are using an outdated PDF. There were erratas of this:

![Bildschirmfoto 2023-06-17 um 19 02 43](https://github.com/Rayji96/foundry-V5/assets/79832708/027036f5-f353-427f-b4aa-1efefbf16ed1)

**Comment by chaosgasket** [comment]
Just for completeness, here is BP 3 , which also has Blood Surge and Bane Severity too high.  It looks like this continues for all of the BPs

I did just upgrade to VTT 11, so maybe that is breaking something.

![Screenshot 2023-06-17 120121](https://github.com/Rayji96/foundry-V5/assets/99540375/ec7cf660-0b35-4f92-95d6-1a073a0c5b23)

**Comment by chaosgasket** [comment]
Ah, that makes sense, I've had this kicking around for a while. Thank you for your help!
